url: 'http://idp/'
clientId: 'clientId'
secret: 'secret'
ssl: true
createIfMissing: true
redirect: 'https://databus.dbpedia.org/forum'
stableRedirect: true
LogoutAllOidcOnForumLogout: false
debug: false


